// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chzpjzambdiyakspllfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNoenBqemFtYmRpeWFrc3BsbGZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MTM4ODYsImV4cCI6MjA3MDA4OTg4Nn0.bXvJwNWDWN8zGCsP8Er4jSld_K9fBNOuunAovnCgomQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});